### ISSUE TITLE
Issues with Docker-compose volumes

### ISSUE THREAD

**Issue by nadrojisk** [JonasBonno/docker-ftb-infinity#2]
I'm trying to create a docker-compose for this just so its easier to spin up the server. However, for some reason I cannot use a volume in the base directory that the container creates. If i use `./minecraft-data:/minecraft/world`. It works, but, if I bind that I can't edit the server properties or other server config files. 
```
version: "3"

services:
  ftb:
    image: jonasbonno/ftb-infinity
    ports:
      - 25567:25565
    tty: true
    stdin_open: true
    restart: always
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/minecraft
    container_name: ftb
```

Running that compose gives me this error. Do you know how I might be able to fix this?
`ftb    | /bin/bash: /minecraft/ServerStart.sh: No such file or directory`
